---
title: "A Cartridge Case Analysis Pipeline"
author: "Joseph Zemmels"
institute: "Center for Statistics and Applications in Forensic Evidence"
date: "2022-06-17"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE,
        echo = FALSE,
        fig.align = 'center')
```


# Acknowledgements

## Funding statement

This work was partially funded by the Center for Statistics and Applications in Forensic Evidence (CSAFE) through Cooperative Agreement 70NANB20H019 between NIST and Iowa State University, which includes activities carried out at Carnegie Mellon University, Duke University, University of California Irvine, University of Virginia, West Virginia University, University of Pennsylvania, Swarthmore College and University of Nebraska, Lincoln.

---

# Outline

- Introduction

- Cartridge Case Comparison Pipelines

- Visual Diagnostics

---

class: inverse, center, middle

# Introduction

---

# Cartridge Cases

---

# Breech Face Impressions

---

# Forensic Examinations

---

# Forensic Comparison Algorithms

Cite NAS, PCAST

Creation of CSAFE

---

# Data Analysis Pipelines

Cite Kiegan's work

---

class: inverse, center, middle

# Cartridge Case Comparison Pipelines

---

class: inverse, center, middle

# Visual Diagnostics

---

