# Automatic Matching of Cartridge Case Impressions

```{block, type='paperinfo_'}
To be submitted in the *Journal of Data Science, Statistics, and Visualizations*
```
```{block, type='paperauthor_'}
Joseph Zemmels and Susan VanderPlas and Heike Hofmann
```

## Abstract {-}

Forensic examinations attempt to solve the binary classification problem of whether two pieces of evidence originated from the same source.
For example, a cartridge case found at a crime scene may be compared to a cartridge case fired from a suspect’s firearm. 
Forensic examiners traditionally rely on high-powered comparison microscopes, case facts, and their own experience to arrive at a source conclusion. 
Recently, algorithms that provide an automatic and objective measure of similarity of the evidence have become more prevalent. 
We introduce the Automatic Cartridge Evidence Scoring (ACES) algorithm that encompasses preprocessing, feature extraction, and similarity scoring. 
Our primary contribution is a set of features used to classify whether two cartridge cases were fired from the same firearm. 
We use a train/test split on a data set of 510 cartridge case scans to fit and validate random forest, logistic regression, and Classification and Regression Tree (CART) models.
We demonstrate that these models are more accurate than predominant algorithms on our data set.

## Introduction

Start of paper.
